### ISSUE TITLE
The manually annotated testing file does not exist.

### ISSUE THREAD

**Issue by Code-kunkun** [facebookresearch/VidDetours#1]
<img width="1010" alt="image" src="https://github.com/facebookresearch/VidDetours/assets/58265850/d637e8c5-e41e-4cd3-b090-fb5bb518e05d">

**Comment by thechargedneutron** [comment]
Hi @Code-kunkun, thanks for pointing it out, here is the corrected link: https://dl.fbaipublicfiles.com/VidDetours/manual_test_set_localization_v3_unique_id.json
